name: Continuous Deployment Development

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Set environment variable
      run: echo "TILEJSON_URL=${{ secrets.TILEJSON_URL_DEV }}" >> $GITHUB_ENV
  
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
    - run: |
        npm ci
        npm run build

    - name: Deploy
      uses: BetaHuhn/do-spaces-action@v2.0.58
      with:
        access_key: ${{ secrets.S3_KEY }}
        secret_key: ${{ secrets.S3_SECRET }}
        space_name: 'w3geo'
        space_region: 'fra1'
        source: 'dist'
        out_dir: ${{ secrets.S3_BUCKET_DEV }}

